java process config:
  max memory gigabytes: 8
  startup commands path: startup-commands.txt
commands port: 8080
server properties:
  difficulty: hard
  motd: Subchat Server
  spawn-protection: "0"
  online-mode: false
  enforce-secure-profile: false
  white-list: true
  enforse-whitelist: true
