name: subchat-mc-server

configs:
  mcconfig:
    file: ${CONFIGS_PATH:-server-configs}/server-config.yaml
  mcstartup:
    file: ${CONFIGS_PATH:-server-configs}/startup-commands.txt
  easyauth:
    file: ${CONFIGS_PATH:-server-configs}/easyauth.json
  tgbot:
    file: ${CONFIGS_PATH:-server-configs}/tg-bot.yaml
  
secrets:
  tgbot-secret:
    file: ${SECRETS_PATH:-secrets}/tgbot.json

networks:
  subchat-ip6net:
    enable_ipv6: true
  subchat-internal:
    internal: true
  external:

services:
  mc-server:
    networks:
      - subchat-ip6net
      - subchat-internal
    build:
      context: .
      dockerfile: mc-server.Dockerfile
      args:
        - WORKUID=${WORKUID:-0}
    ports:
      - ${OVERSEER_IP}${OVERSEER_IP:+:}8080:8080
    stdin_open: true
    tty: true
    # command: bash    
    configs:
      - source: mcconfig
        target: /mcserver/server-config.yaml
      - source: mcstartup
        target: /mcserver/startup-commands.txt
      - source: easyauth
        target: /mcserver/mods/EasyAuth/config.json
    volumes:
      - type: bind
        source: ${STORAGE_PATH:-storage}/world
        target: /mcserver/world
      - type: bind
        source: ${STORAGE_PATH:-storage}/playes-lists
        target: /mcserver/player-lists
      - type: bind
        source: ${STORAGE_PATH:-storage}/easyauth-leveldb
        target: /mcserver/mods/EasyAuth/levelDBStore
  mc-proxy:
    networks:
      - subchat-internal
      - external # need to bind
    build:
      context: .
      dockerfile: mc-proxy.Dockerfile
      args:
        - WORKUID=${WORKUID:-0}
    ports:
      - ${SERVER_IP}${SERVER_IP:+:}25565:25565
    volumes:
      - type: bind
        source: ${CONFIGS_PATH:-server-configs}/mc-proxies
        target: /infrared/proxies
        read_only: true
  tg-bot:
    networks:
      - subchat-internal
      - external
    build:
      context: .
      dockerfile: tg-bot.Dockerfile
      args:
        - WORKUID=${WORKUID:-0}
    configs:
      - source: tgbot
        target: /tgbot/config.yaml
    secrets:
      - tgbot-secret
    volumes:
      - type: bind
        source: ${STORAGE_PATH:-storage}/bot-db
        target: /sqlite
