name: subchat-mc-server

volumes:
  mcworld:

services:
  mc-server:
    build:
      context: .
      dockerfile: mc-server.Dockerfile
    volumes:
      - type: bind
        source: minecraft-server/config
        target: /mcserver/config
        volume:
          nocopy: true
      - type: volume
        source: mcworld
        target: /mcserver/world
        volume:
          nocopy: true
  infrared:
    build:
      context: .
      dockerfile: infrared.Dockerfile
    ports:
      - 100.126.72.77:25565:25565
    volumes:
      - type: bind
        source: mc-proxies/imobul.us.yaml
        target: /infrared/proxies
