name: subchat-mc-server

volumes:
  mcworld:
  mclists:
  easyauth-storage:

configs:
  mcconfig:
    file: ./minecraft-server/server-config.yaml
  mcstartup:
    file: ./minecraft-server/startup-commands.txt
  
secrets:
  tgbot-secret:
    file: ./secrets/tgbot.json

services:
  mc-server:
    build:
      context: .
      dockerfile: mc-server.Dockerfile
    ports:
      - 100.126.72.77:8080:8080
    stdin_open: true
    tty: true
    # command: bash    
    configs:
      - source: mcconfig
        target: /mcserver/server-config.yaml
      - source: mcstartup
        target: /mcserver/startup-commands.txt
    volumes:
      - type: volume
        source: mcworld
        target: /mcserver/world
        volume:
          nocopy: true
      - type: volume
        source: mclists
        target: /mcserver/player-lists
        volume:
          nocopy: true
      - type: volume
        source: easyauth-storage
        target: /mcserver/mods/EasyAuth/levelDBStore
        volume:
          nocopy: true
  mc-proxy:
    build:
      context: .
      dockerfile: mc-proxy.Dockerfile
    ports:
      - 100.126.72.77:25565:25565
    volumes:
      - type: bind
        source: mc-proxies
        target: /infrared/proxies
        read_only: true
