name: subchat-mc-server

configs:
  mcconfig:
    file: ${CONFIGS_PATH:-server-configs}/server-config.yaml
  mcstartup:
    file: ${CONFIGS_PATH:-server-configs}/startup-commands.txt
  
secrets:
  tgbot-secret:
    file: ${SECRETS_PATH:-secrets}/tgbot.json

services:
  mc-server:
    build:
      context: .
      dockerfile: mc-server.Dockerfile
    ports:
      - ${OVERSEER_IP}${OVERSEER_IP:+:}8080:8080
    stdin_open: true
    tty: true
    # command: bash    
    configs:
      - source: mcconfig
        target: /mcserver/server-config.yaml
      - source: mcstartup
        target: /mcserver/startup-commands.txt
    volumes:
      - type: bind
        source: ${STORAGE_PATH:-storage}/world
        target: /mcserver/world
      - type: bind
        source: ${STORAGE_PATH:-storage}/playes-lists
        target: /mcserver/player-lists
      - type: bind
        source: ${STORAGE_PATH:-storage}/easyauth-leveldb
        target: /mcserver/mods/EasyAuth/levelDBStore
    user: ${SERVER_USER:-${USER}}:${SERVER_USER:-${USER}}
  mc-proxy:
    build:
      context: .
      dockerfile: mc-proxy.Dockerfile
    ports:
      - ${SERVER_IP}${SERVER_IP:+:}25565:25565
    volumes:
      - type: bind
        source: ${CONFIGS_PATH:-server-configs}/mc-proxies
        target: /infrared/proxies
        read_only: true
    user: ${SERVER_USER:-${USER}}:${SERVER_USER:-${USER}}
  tg-bot:
    build:
      context: .
      dockerfile: tg-bot.Dockerfile
    secrets:
      - tgbot-secret
    volumes:
      - type: bind
        source: ${STORAGE_PATH:-storage}/bot-db
        target: /sqlite
    user: ${SERVER_USER:-${USER}}:${SERVER_USER:-${USER}}
