java process config:
  max memory gigabytes: 8
  startup commands path: /mcserver/external-server-config/startup-commands.txt
commands port: 8080
server properties:
  difficulty: hard
  motd: Subchat Server
  spawn-protection: "0"
  online-mode: true
  enforce-secure-profile: false
